* 12. [2015-09-17 Thu 17:19]
** [[https://argcv.com/articles/3207.c][格式化MongoDB的输出]] [2015-09-17 Thu 17:19]

# 11、2015-07-21
* [MongoDB CRUD Operations > MongoDB CRUD Tutorials > Remove Documents](http://docs.mongodb.org/manual/tutorial/remove-documents/)

  In MongoDB, the db.collection.remove() method removes documents from a collection. You can remove all documents from a collection, remove all documents that match a condition, or limit the operation to remove just a single document.

  > remove

# 10、2015-07-18
* [Reference > Operators > Query and Projection Operators > Comparison Query Operators > $nin](http://docs.mongodb.org/manual/reference/operator/query/nin/#op._S_nin)

# 9、2015-07-06
* [Reference > Operators > Update Operators > Field Update Operators > $inc](http://docs.mongodb.org/manual/reference/operator/update/inc/#up._S_inc)

  The $inc operator increments a field by a specified value and has the following form:
  { $inc: { <field1>: <amount1>, <field2>: <amount2>, ... } }

# 8、2015-07-02
* [Mongodb数据更新命令、操作符](http://chenzhou123520.iteye.com/blog/1637629)

  > update

* [Reference > mongo Shell Methods > Collection Methods > db.collection.update()](http://docs.mongodb.org/manual/reference/method/db.collection.update/#db.collection.update)

  Modifies an existing document or documents in a collection. The method can modify specific fields of an existing document or documents or replace an existing document entirely, depending on the update parameter.

  > update

# 7、2015-06-23
* [MongoDB 使用的一些经验](http://blog.eood.cn/mongodb)

  这是一篇关于 MongoDB 使用经验的一篇文章，MongoDB 相对于 MySQL 简单很多，关于 MySQL 的调优可以看另一篇博文： MYSQL 调优和使用必读。

  > nodejs

# 6、2015-06-17
* [Nosql之Mongodb 2 高级查询](http://www.cnblogs.com/zhaoyang/archive/2012/01/10/2317664.html)

# 5、2015-06-13
* [mongoDB中文社区](http://www.mongoing.com/)

  MongoDB是当前最受欢迎的新一代数据库。迄今为止已经有接近800万下载。使用MongoDB的用户包括财富500公司如eBay, Cisco, MetLife, Adobe等等。相比于传统关系数据库，MongoDB对于大数据，高并发以及高可靠性有强大的支持。相比于其他的NoSQL数据库，MongoDB的基于文档的数据模型及其动态建模的特性使得它更加自由灵活，适用于各种应用场景如CRM，内容管理，事件纪录，商情分析，手机应用，社交等等。但是MongoDB的最大优势在于其庞大的社区。根据非正式统计，目前有20多万MongoDB网络大学的注册学生，3万多线下用户组成员。全世界各地都有MongoDB的技术交流活动。

  建立mongoing.com社区的目的是希望可以有一个专门的社区让喜欢MongoDB的技术人员有一个集中交流的地方。根据Google Trend的统计，搜索MongoDB最多的十大城市中中国占了4个，前三名分别是 北京，深圳和上海。与此不相符的是MongoDB的零散的中文资源。 这个社区初步计划会有以下版块：

  * 博客， 定期撰写或转载有关性能调试，数据库模型设计等博文，也会翻译一些受欢迎的英文博客
  * 问答，一个将有国内一些MongoDB大牛和MongoDB公司的高级技术人员参与的互动互助平台，解决目前Google User Group不稳定的问题
  * 线下用户组，组织发展各地的定期线下活动。

  如果你有兴趣一起参与建设这个社区，例如发表博文，组织线下活动等等，请联系[@TJ_MongoDB](http://www.weibo.com/mongoing)。

# 4、2015-06-03
* [replSetGetConfig](http://docs.mongodb.org/manual/reference/command/replSetGetConfig/)

  New in version 3.0.0.

* [Compatibility Changes in MongoDB 3.0](http://docs.mongodb.org/manual/release-notes/3.0-compatibility/)

  The following 3.0 changes can affect the compatibility with older versions of MongoDB. See Release Notes for MongoDB 3.0 for the full list of the 3.0 changes.

* [MongoDB Backup Methods](http://docs.mongodb.org/manual/core/backups/)

  When deploying MongoDB in production, you should have a strategy for capturing and restoring backups in the case of data loss events. There are several ways to back up MongoDB clusters:

  * Backup by Copying Underlying Data Files
  * Backup a Database with mongodump
  * MongoDB Management Service (MMS) Cloud Backup
  * MongoDB Management Service (MMS) Ops Manager Backup Software

* [Resync a Member of a Replica Set](http://docs.mongodb.org/manual/tutorial/resync-replica-set-member/)

  A replica set member becomes “stale” when its replication process falls so far behind that the primary overwrites oplog entries the member has not yet replicated. The member cannot catch up and becomes “stale.” When this occurs, you must completely resynchronize the member by removing its data and performing an initial sync.

* [Analyze Query Performance](http://docs.mongodb.org/manual/tutorial/analyze-query-plan/)

  The cursor.explain("executionStats") and the db.collection.explain("executionStats") methods provide statistics about the performance of a query. This data output can be useful in measuring if and how a query uses an index.

# 3、2015-06-02
* [MongoDB CRUD Operations > MongoDB CRUD Tutorials > Limit Fields to Return from a Query](http://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/)

  The projection document limits the fields to return for all matching documents. The projection document can specify the inclusion of fields or the exclusion of fields.

# 2、2015-06-01
* [Server Status Output](http://docs.mongodb.org/manual/reference/server-status/)

  This document provides a quick overview and example of the serverStatus command. The helper db.serverStatus() in the mongo shell provides access to this output.

* [Reference > mongo Shell Methods > Cursor Methods > cursor.explain()](http://docs.mongodb.org/manual/reference/method/cursor.explain/)

  Changed in version 3.0: The parameter to the method and the output format have changed in 3.0.

* [Administration > Administration Tutorials > MongoDB Scripting > Server-side JavaScript](http://docs.mongodb.org/v2.6/core/server-side-javascript/)

  MongoDB provides the following commands, methods, and operator that perform server-side execution of JavaScript code

# 1、2015-05-29
* [Configuration File Options](http://docs.mongodb.org/manual/reference/configuration-options/)

  You can control mongod and mongos instances at runtime using a configuration file. The configuration file contains settings that are functionally equivalent to the mongod and mongos command-line arguments but are easier to manage, especially on large-scale deployments. Configuration files allow commenting to describe the reasoning behind a server’s settings.

* [Manage mongod Processes](http://docs.mongodb.org/manual/tutorial/manage-mongodb-processes/#terminate-mongod-processes)

  MongoDB runs as a standard program. You can start MongoDB from a command line by issuing the mongod command and specifying options. For a list of options, see the mongod reference. MongoDB can also run as a Windows service. For details, see Manually Create a Windows Service for MongoDB. To install MongoDB, see Install MongoDB.
